# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_2OcMwCl1DKXjIDCAWRaIO6GHuhkGD_
"""

# =====================================
# IMPORT LIBRARY
# =====================================
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

# =====================================
# STREAMLIT CONFIG
# =====================================
st.set_page_config(
    page_title="Fraud Detection System",
    page_icon="🛡️",
    layout="centered"
)

st.title("🛡️ Fraud Detection System")
st.write(
    "Aplikasi deteksi penipuan transaksi menggunakan "
    "Random Forest dan Complement Naive Bayes"
)

# =====================================
# LOAD MODELS
# =====================================
@st.cache_resource
def load_models():
    models = {
        "RF Baseline CV 3": "rf_baseline_cv3.pkl",
        "RF Baseline CV 5": "rf_baseline_cv5.pkl",
        "RF Tuned CV 3": "rf_tuned_cv3.pkl",
        "RF Tuned CV 5": "rf_tuned_cv5.pkl",
        "CNB Baseline CV 3": "cnb_baseline_cv3.pkl",
        "CNB Baseline CV 5": "cnb_baseline_cv5.pkl",
        "CNB Tuned CV 3": "cnb_tuned_cv3.pkl",
        "CNB Tuned CV 5": "cnb_tuned_cv5.pkl",
    }

    loaded_models = {}

    for name, path in models.items():
        if not os.path.exists(path):
            st.error(f"File model tidak ditemukan: {path}")
            st.stop()

        bundle = joblib.load(path)

        # Validasi isi bundle
        required_keys = ["model", "features"]
        for key in required_keys:
            if key not in bundle:
                st.error(f"Model {name} tidak memiliki key '{key}'")
                st.stop()

        loaded_models[name] = bundle

    return loaded_models


MODELS = load_models()

# =====================================
# PILIH MODEL
# =====================================
st.sidebar.header("⚙️ Konfigurasi Model")

model_name = st.sidebar.selectbox(
    "Pilih Model",
    list(MODELS.keys())
)

bundle = MODELS[model_name]

model = bundle["model"]
features = bundle["features"]
scaler = bundle.get("scaler", None)
selector = bundle.get("feature_selector", None)

st.sidebar.success(bundle.get("model_type", model_name))

# =====================================
# INPUT DATA
# =====================================
st.subheader("🧾 Input Data Transaksi")

with st.form("fraud_form"):
    col1, col2 = st.columns(2)

    with col1:
        purchase_value = st.number_input(
            "Purchase Value", min_value=1.0, value=35.0
        )
        device_freq = st.number_input(
            "Device Frequency", min_value=0, value=1
        )
        ip_freq = st.number_input(
            "IP Frequency", min_value=0, value=1
        )

    with col2:
        time_diff = st.number_input(
            "Time Difference (detik)", min_value=0.0, value=300.0
        )
        source_direct = st.selectbox("Source Direct", [0, 1])
        source_seo = st.selectbox("Source SEO", [0, 1])
        browser_ie = st.selectbox("Browser IE", [0, 1])
        value_group_medium = st.selectbox("Value Group Medium", [0, 1])

    submit = st.form_submit_button("🔍 Prediksi")

# =====================================
# PREDIKSI
# =====================================
if submit:
    X_input = pd.DataFrame([{
        "device_freq": device_freq,
        "ip_freq": ip_freq,
        "time_diff": time_diff,
        "source_Direct": source_direct,
        "source_SEO": source_seo,
        "browser_IE": browser_ie,
        "value_group_medium": value_group_medium,
        "purchase_value": purchase_value
    }])

    # Samakan urutan fitur
    try:
        X_input = X_input[features]
    except KeyError as e:
        st.error(f"Fitur input tidak cocok dengan model: {e}")
        st.stop()

    # Scaling
    if scaler is not None:
        X_input = scaler.transform(X_input)

    # Feature selection
    if selector is not None:
        X_input = selector.transform(X_input)

    # Prediksi
    y_pred = model.predict(X_input)[0]

    # Probabilitas
    if hasattr(model, "predict_proba"):
        prob = model.predict_proba(X_input)[0][1]
        st.metric("Probabilitas Fraud", f"{prob:.2%}")

    st.markdown("---")
    st.subheader("📊 Hasil Prediksi")

    if y_pred == 1:
        st.error("🚨 TRANSAKSI TERINDIKASI FRAUD")
    else:
        st.success("✅ TRANSAKSI NORMAL (LEGIT)")

# =====================================
# FOOTER
# =====================================
st.markdown("---")
st.caption("Fraud Detection System | Random Forest & Complement Naive Bayes")

